export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const SHOP_LIST_REQUEST='SHOP_LIST_REQUEST';
export const OUTLET_LIST_REQUEST='OUTLET_LIST_REQUEST';