export const FETCH_CART_REQUEST = "FETCH_CART_REQUEST";
export const FETCH_CART_SUCCESS = "FETCH_CART_SUCCESS";
export const FETCH_CART_FAILURE = "FETCH_CART_FAILURE";

export const ADD_UPDATE_CART_REQUEST = "ADD_UPDATE_CART_REQUEST";
export const ADD_UPDATE_CART_SUCCESS = "ADD_UPDATE_CART_SUCCESS";
export const ADD_UPDATE_CART_FAILURE = "ADD_UPDATE_CART_FAILURE";
